server:
  port: 8080

jwt:
  #ssecret property 로 관리 필요
  header: Authorization
  secret: Y2hvcHBhLWRvbnQtYml0ZS1tZS1zcHJpbmctYm9vdC1qd3QtdGVzdC1zZWNyZXQta2V5LWNob3BwYS1kb250LWJpdGUtbWUtc3ByaW5nLWJvb3Qtand0LXRlc3Qtc2VjcmV0LWtleQo=
  token-validity-in-seconds: 86400

#spring:
aes:
  encrypt:
    key: ${ENCRYPT_KEY}


spring:
  modulith:
    events:
      jdbc-schema-initialization:
        enabled: true
    #  datasource:
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: org.postgresql.Driver
      pool-name: HikariCP4Master
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  #JPA
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
    defer-datasource-initialization: true

# RabbitMQ 연결 정보
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# redis
  data:
    redis:
      host: localhost
      port: 6379

# RabbitMQ queue, exchange, routing-key 정보
rabbitmq:
  queue:
    name: missionary
  exchange:
    name: missionary.exchange
  routing:
    key: missionary.key
